image: node:12.18.3

pipelines:
  default:
    - step:
        name: Test
        script:
          - npm install && npm test 

    - step:
        name: Build
        script:
          - npm install && npm run build 
        artifacts:
          - build/**
          
    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - pipe: atlassian/firebase-deploy:0.4.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT